---
services:

  # Emby media server
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Amsterdam
    volumes:
    - /opt/arr-stack/emby:/config
    - /opt/arr-stack:/opt/arr-stack
    ports:
    - 8096:8096
    restart: unless-stopped

  # Sonarr for movie management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Amsterdam
    volumes:
    - /opt/arr-stack/sonarr:/config
    - /opt/arr-stack:/opt/arr-stack
    ports:
    - 8989:8989
    restart: unless-stopped

  # Radarr for movie management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Amsterdam
    volumes:
    - /opt/arr-stack/radarr:/config
    - /opt/arr-stack:/opt/arr-stack
    ports:
    - 7878:7878
    restart: unless-stopped

  # Bazarr for subtitle management
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Amsterdam
    volumes:
    - /opt/arr-stack/bazarr:/config
    - /opt/arr-stack:/opt/arr-stack
    ports:
    - 6767:6767
    restart: unless-stopped

  # Prowlarr for indexer management
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Amsterdam
    volumes:
    - /opt/arr-stack/prowlarr:/config
    ports:
    - 9696:9696
    restart: unless-stopped

  # Deluge for torrent downloading
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Amsterdam
    volumes:
    - /opt/arr-stack/deluge:/config
    - /opt/arr-stack:/opt/arr-stack
    ports:
    - 8112:8112
    - 6881:6881
    - 6881:6881/udp
    restart: unless-stopped
