services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    env_file: ".env"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565"
      - "19132:19132/udp"
      - "24454:24454/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - ./logs:/var/log/caddy